# Generated by Django 4.2.15 on 2024-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament_display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
