# Generated by Django 4.2.15 on 2024-11-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_player_cover_alter_player_avatar_playerstats_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
