# Generated by Django 4.2.15 on 2024-10-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_player_cover_alter_player_avatar_playerstats_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='otp_secret_key',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
