# Generated by Django 4.2.15 on 2024-11-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_playerstats_user_id_delete_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='otp_secret_key',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
