############################################################
######## RESTFULL PROFILES === GET PUT PATCH === ONLY ################################################################################
############################################################

#########
GET http://localhost:8080/accounts/rest-profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

#########
GET http://localhost:8080/accounts/rest-profiles/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

######### # display name is required
PUT http://localhost:8080/accounts/rest-profiles/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A
Content-Type: application/json

{
    "display_name": "rambeaxu_qn56e5us8x4y",
    "bio": "bsdadsad",
    "avatar": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    "cover": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}

#########
PATCH http://localhost:8080/accounts/rest-profiles/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A
Content-Type: application/json

{
    "avatar":"https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}


######## ACHIVEMENT SPECS === GET === ONLY ################################################################################

#########
GET http://localhost:8080/accounts/rest-achievements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A


#########
GET http://localhost:8080/accounts/rest-achievements/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

######### HISTORY SPECS === GET === ONLY ######################################################################################

#########
GET http://localhost:8080/accounts/rest-historys/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

#########
GET http://localhost:8080/accounts/rest-historys/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

############################################################
######## USER SPECS === GET PUT PATCH === ONLY ################################################################################
############################################################

#########
GET http://localhost:8080/accounts/user-profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

#########
PUT http://localhost:8080/accounts/user-profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A
Content-Type: application/json

{
    "display_name": "deeerooo23123"
}

#########
PATCH http://localhost:8080/accounts/user-profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A
Content-Type: application/json

{
    "bio":"droitx"
}


####################################################################################################################################
=
#########
GET http://localhost:8080/accounts/user-settings/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MTExNDM1LCJpYXQiOjE3MzU4NTIyMzUsImp0aSI6ImU0ZjlmZTIxYzk1NTRkYWQ4NWEzNWYzOTFmZmRlNjUxIiwidXNlcl9pZCI6Mn0.ePsIR8W6BOtTS12a2RkebZRUdQjk8IK1dgcfvI2C6CQ

#########
PUT http://localhost:8080/accounts/user-settings/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MTExNDM1LCJpYXQiOjE3MzU4NTIyMzUsImp0aSI6ImU0ZjlmZTIxYzk1NTRkYWQ4NWEzNWYzOTFmZmRlNjUxIiwidXNlcl9pZCI6Mn0.ePsIR8W6BOtTS12a2RkebZRUdQjk8IK1dgcfvI2C6CQ
Content-Type: application/json

{
  "private_profile": true
  "notifications_enabled": 
}

#########
PATCH http://localhost:8080/accounts/user-settings/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A
Content-Type: application/json

{
    "private_profile": true,
}

####################################################################################################################################

#########
GET http://localhost:8080/accounts/user-history/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

####################################################################################################################################

#########
GET http://localhost:8080/accounts/user-achievements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

####################################################################################################################################


############################################################
######### LEADERBOARD SPECS === GET === ONLY ######################################################################################
############################################################

#########
GET http://localhost:8080/accounts/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A


############################################################
######### SEARCH SPECS === GET === ONLY ######################################################################################
############################################################
#########
GET http://localhost:8080/accounts/search-users/?search=c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

# ######### search friends
# GET http://localhost:8080/accounts/search-users/?search=admin
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A

###############################
# GET http://localhost:8080/accounts/settings/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A


######################
GET http://localhost:8080/accounts/user-player/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A


######################
POST http://localhost:8080/accounts/user-player/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDUzMjgzLCJpYXQiOjE3MzU3OTQwODMsImp0aSI6IjRmNjM0N2E0MzMzYjQwN2M4ODk3OWQzNWMzZTBmM2NhIiwidXNlcl9pZCI6MTJ9.Do7JNV_AtIxtg1th_e4eK3KooA78ByPJROreW8P4F8A
Content-Type: application/json

{
    "new_password": "123456789",
    "old_password": "password"
}

###########
POST http://localhost:8080/accounts/2fa/generate-uri/
Content-Type: application/json

{
    "username": "mery"
}