############################################################
######## RESTFULL PROFILES === GET PUT PATCH === ONLY ################################################################################
############################################################

#########
GET http://localhost:8080/api/accounts/rest-profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

#########
GET http://localhost:8080/api/accounts/rest-profiles/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

#########
PUT http://localhost:8080/api/accounts/rest-profiles/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk
Content-Type: application/json

{
    "display_name": "rambeaxu_qn56e5us8x4y",
    "bio": "bsdadsad",
}

#########
PATCH http://localhost:8080/api/accounts/rest-profiles/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk
Content-Type: application/json

{
    "avatar":"https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}


######## ACHIVEMENT SPECS === GET === ONLY ################################################################################

#########
GET http://localhost:8080/api/accounts/rest-achievements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk


#########
GET http://localhost:8080/api/accounts/rest-achievements/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

######### HISTORY SPECS === GET === ONLY ######################################################################################

#########
GET http://localhost:8080/api/accounts/rest-historys/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

#########
GET http://localhost:8080/api/accounts/rest-historys/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

############################################################
######## USER SPECS === GET PUT PATCH === ONLY ################################################################################
############################################################

#########
GET http://localhost:8080/api/accounts/user-profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

#########
PUT http://localhost:8080/api/accounts/user-profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk
Content-Type: application/json

{
    "display_name": "deeerooo23123"
}

#########
PATCH http://localhost:8080/api/accounts/user-profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk
Content-Type: application/json

{
    "display_name": "deeerooo23123xasdasd",
    "bio":"droitx"
}


####################################################################################################################################
=
#########
GET http://localhost:8080/api/accounts/user-settings/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

#########
PUT http://localhost:8080/api/accounts/user-settings/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk
Content-Type: application/json

{
  "private_profile": true
  "notifications_enabled":
}

#########
PATCH http://localhost:8080/api/accounts/user-settings/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk
Content-Type: application/json

{
    "private_profile": true,
}

####################################################################################################################################

#########
GET http://localhost:8080/api/accounts/user-history/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

####################################################################################################################################

#########
GET https://localhost:443/api/accounts/user-achievements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MTEzNjI5LCJpYXQiOjE3MzYxMTAwMjksImp0aSI6ImE4YWIyYTgyZTI1MjQ2NWI4Mjc4ZGY2NjU1ZWRjMmRmIiwidXNlcl9pZCI6Mn0.RxIh9HgMufUGPr0BBMXkVrXKCTxpqjpJe2GKvE4qaHA

####################################################################################################################################


############################################################
######### LEADERBOARD SPECS === GET === ONLY ######################################################################################
############################################################

#########
GET http://localhost:8080/api/accounts/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk


############################################################
######### SEARCH SPECS === GET === ONLY ######################################################################################
############################################################
#########
GET http://localhost:8080/api/accounts/search-users/?search=c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

# ######### search friends
# GET http://localhost:8080/api/accounts/search-users/?search=admin
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk

###############################
# GET http://localhost:8080/api/accounts/settings/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk


######################
GET http://localhost:8080/api/accounts/user-player/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk


######################
POST http://localhost:8080/api/accounts/user-player/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTc2OTIzLCJpYXQiOjE3MzY3MTc3MjMsImp0aSI6ImUxNWVjM2QzYmZmMDRhYzI4ZmRkYTg1OTU1NTcyYjZhIiwidXNlcl9pZCI6NH0.dAhDclVPGTNIpjFlGZ6-9DyhnBA6xFPThU5ZfjbzhCk
Content-Type: application/json

{
    "new_password": "123456789",
    "old_password": "password"
}

###########
POST http://localhost:8080/accounts/2fa/generate-uri/
Content-Type: application/json

{
    "username": "mery"
}
