version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: