
###########################
######### GET #############
###########################
#review methods
#########
GET http://localhost:8080/relations/players/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA

######### i dont see why u gonna need 2 fileds returned where one is ur self

GET http://localhost:8080/relations/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA

#############
DELETE http://localhost:8080/relations/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA
Content-Type: application/json

{
    "remove_friend":"client5_2pml18r8gmtb"
}

######### protect api against sending a friend request to from both users me pending him pending
GET http://localhost:8080/relations/friends/pending/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA

#############
DELETE http://localhost:8080/relations/friends/pending/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA
Content-Type: application/json

{
    "decline_pending":"client1_o69rsvl8omls"
}

#########
GET http://localhost:8080/relations/notifications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA

############################
######### invite #############
############################


#########
GET http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA


#########
POST http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA
Content-Type: application/json

{
    "receiver":"client1_o69rsvl8omls"
}

#########
DELETE http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA
Content-Type: application/json

{
    "cancel_invite":"client1_o69rsvl8omls"
}



##########################################
POST http://localhost:8080/relations/friends/accept/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA
Content-Type: application/json

{
    "sender":"client2_yftrblf5mvwt"
}

############################################
########## GET / PATCH / DELETE ############
############################################

#########
GET http://localhost:8080/relations/friends/block/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA

#########
POST http://localhost:8080/relations/friends/block/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA
Content-Type: application/json

{
    "block_user" : "client4_2scdr98a7xkt"
}

#########
DELETE http://localhost:8080/relations/friends/block/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTk3MTg2LCJpYXQiOjE3MzU1OTQ3ODYsImp0aSI6IjY0NTIyYzgwODUwZTRjNjY5ZWRiMmNjNWM4MmU1NmNhIiwidXNlcl9pZCI6NH0.y2ZxDcBJ9Ht0jY7KnIhtA8lqGBeH8zOiZwp-cY9csCA
Content-Type: application/json

{
    "unblock_user" : "client4_2scdr98a7xkt"
}
