############################
######### GET #############
############################
#review methods
#########
GET http://localhost:8080/relations/players/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4

######### i dont see why u gonna need 2 fileds returned where one is ur self
GET http://localhost:8080/relations/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4

#############
# DELETE http://localhost:8080/relations/friends/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4
# Content-Type: application/json

# {
#     "remove_friend":"client2_ya52hhkjc6wl"
# }

######### protect api against sending a friend request to from both users me pending him pending
GET http://localhost:8080/relations/friends/pending/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4

#############
# DELETE http://localhost:8080/relations/friends/pending/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4
# Content-Type: application/json

# {
#     "decline_pending":"client2_ya52hhkjc6wl"
# }

#########
GET http://localhost:8080/relations/notifications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4

############################
######### POST #############
############################


#########
POST http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4
Content-Type: application/json

{
    "receiver":"client2_ya52hhkjc6wl"
}

#########
# DELETE http://localhost:8080/relations/friends/invite/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4
# Content-Type: application/json

# {
#     "cancel_invite":"client2_ya52hhkjc6wl"
# }

#########
POST http://localhost:8080/relations/friends/accept/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4
Content-Type: application/json

{
    "sender":"client2_yftrblf5mvwt"
}

############################################
########## GET / PATCH / DELETE ############
############################################

#########
GET http://localhost:8080/relations/friends/block/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4

#########
POST http://localhost:8080/relations/friends/block/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4
Content-Type: application/json

{
    "block_user" : "client2_ya52hhkjc6wl"
}

#########
DELETE http://localhost:8080/relations/friends/block/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0OTM3MTA3LCJpYXQiOjE3MzQ5MzQ3MDcsImp0aSI6ImQ1MWFiZGQ5ODM0OTRhY2I4MTkxMmM2OGNjMGQ5YTI3IiwidXNlcl9pZCI6NH0.Ga4fxjhdU6JBXZNaZSADJKApDkPODT1P84xGs-Z6Mu4
Content-Type: application/json

{
    "unblock_user" : "client2_ya52hhkjc6wl"
}


# status for restful profile api     ==== friend, pending, blocked, none

# none status bottons
    # add friend
    # block

# friend status bottons
    #remove friend
    # block will  result in removing friendship

# recived_invite status bottons
    # decline invite

# sent_invite status bottons
    # cancel invite

# blocked_you status bottons
    # nothing


# blocked_him status bottons
    # unblock user which will remove from blocked list









# blocked status bottons
    #unblock user which will remove from blocked list and add to friends list
