groups:
  - name: cadvisor_alerts
    rules:
      - alert: HighCPUUsage
        expr: avg(rate(container_cpu_usage_seconds_total[5m])) by (container) > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage in container"
          description: "CPU usage exceeds 90% for 5 minutes."

      - alert: HighMemoryUsage
        expr: avg(container_memory_usage_bytes{container!="", container!="POD"}) by (container) / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in container"
          description: "Memory usage exceeds 90% for 5 minutes."

  - name: nginx_alerts
    rules:
      - alert: NginxHighRequestLatency
        expr: rate(nginx_http_request_duration_seconds_sum[5m]) / rate(nginx_http_requests_total[5m]) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High request latency in Nginx"
          description: "Nginx has an average request latency exceeding 1 second."

      - alert: NginxHighErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.*"}[5m]) > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate in Nginx"
          description: "Nginx is returning more than 10 5xx errors in 5 minutes."

  - name: django_alerts
    rules:
      - alert: DjangoHighErrorRate
        expr: rate(django_request_errors_total[5m]) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate in Django"
          description: "Django has more than 1 error per minute."

      - alert: DjangoHighResponseTime
        expr: rate(django_http_request_duration_seconds_sum[5m]) / rate(django_http_requests_total[5m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time in Django"
          description: "Django's average response time exceeds 2 seconds for 5 minutes."

  - name: redis_alerts
    rules:
      - alert: HighMemoryUsageRedis
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage exceeds 80% for 5 minutes."

      - alert: RedisKeyEvictions
        expr: redis_evicted_keys > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Redis key evictions"
          description: "Redis is evicting keys, which indicates high memory pressure."

  - name: postgres_alerts
    rules:
      - alert: HighPostgresLatency
        expr: rate(pg_stat_statements_avg_time{job="postgres"}[5m]) > 500
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High PostgreSQL query latency"
          description: "PostgreSQL query latency exceeds 500ms for 5 minutes."

      - alert: HighPostgresConnections
        expr: pg_stat_activity_count{state="active"} > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of PostgreSQL connections"
          description: "PostgreSQL has more than 100 active connections."
