export const FChatProps = [
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you? I have been trying to reach you and beat you in a game againe and againe hhhhh i am the winner as always',
    time: '12:00',
    unread: 2,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 2,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
  {
    name: 'John Doe',
    imageutl: '/logo.svg',
    text: 'Hello, how are you?',
    time: '12:00',
    unread: 0,
  },
];
