export const LeaderBoard = [
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
  {
    name: 'Noureddine Akebli',
    profilePhoto: '/Avatar.svg',
    level: 22,
    conversationLink: '/conversation/1',
    wins: 10,
  },
];
