export const MatchHistory = [
    {
        player1: 'noureddin',
        player2: 'Player 2',
        player1Score: 3,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    },
    {
        player1: 'Player 1',
        player2: 'Player 2',
        player1Score: 11,
        player2Score: 7,
        player1Photo: '/Avatar.svg',
        player2Photo: '/Avatar.svg',
        player1Level: 22,
        player2Level: 22,
        player1Wins: 10,
        player2Wins: 8,
    }
];