export const UsersList = [
  {
    id: 1,
    name: 'Hajar',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 2,
    name: 'nouredine',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 3,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "-18",
    score: 16,
  },
  {
    id: 4,
    name: 'John Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 5,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 6,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 7,
    name: 'John Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory:" +5",
    score: 16,
  },
  {
    id: 8,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 9,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 10,
    name: 'kawtar',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 11,
    name: 'omar',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+12",
    score: 16,
  },
  {
    id: 12,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 13,
    name: 'John Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "-10",
    score: 16,
  },
  {
    id: 14,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 15,
    name: 'youssraaa',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 16,
    name: 'John Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 17,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 18,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 19,
    name: 'noureddin',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 20,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 21,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 22,
    name: 'test',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 23,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 24,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 25,
    name: 'John Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 26,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 27,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 28,
    name: 'John Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 29,
    name: 'Jane Doe',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
  {
    id: 30,
    name: 'Meryeme',
    ProfilePhoto: '/Avatar.svg',
    level: 'Level 22',
    scoreHistory: "+10",
    score: 16,
  },
];
