# Generated by Django 4.2.15 on 2024-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_tournament_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='templates/account/defaultAvatar.jpeg', upload_to='templates/account/'),
        ),
    ]
