# Generated by Django 4.2.15 on 2024-09-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enabled_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
