# Generated by Django 4.2.15 on 2024-09-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_player_enabled_2fa_player_otp_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='verified_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='otp_secret_key',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
