# Generated by Django 4.2.15 on 2024-09-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_player_ola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ola',
        ),
    ]
