# Generated by Django 4.2.15 on 2024-10-25 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_player_ola'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cover',
            field=models.ImageField(default='Covers/defaultCover.jpeg', upload_to='Covers/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='Avatars/defaultAvatar.jpeg', upload_to='Avatars/'),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_requester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requester', to=settings.AUTH_USER_MODEL)),
                ('friend_responder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_responder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
