
route:
  group_by: ['alertname', 'job']

  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1s

  receiver: 'discord'

receivers:
  - name: 'discord'
    webhook_configs:
      - url: 'http://disord-alerts:9094'
        send_resolved: true
