FROM python:3.8-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY ./config /app/config

WORKDIR /app/source

# RUN apt update && apt install wget -y
# RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.1.1/node_exporter-1.1.1.linux-amd64.tar.gz

# RUN tar xvfz node_exporter-*.*-amd64.tar.gz
# RUN ./node_exporter & in the background

RUN chmod -R +x /app/config \
    && pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

ENTRYPOINT [ "sh", "/app/config/autoLaunch.sh" ]
CMD [ "python", "manage.py", "runsever", "0.0.0.0:8080"]


# curl http://backend:9100/metrics for metrics
