FROM python:alpine

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY . /app

WORKDIR /app/source

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && chmod -R +x /app

# RUN mkdir -p /app/staticfiles/
# RUN apt update && apt install wget -y
# RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.1.1/node_exporter-1.1.1.linux-amd64.tar.gz

# RUN tar xvfz node_exporter-*.*-amd64.tar.gz
# RUN ./node_exporter & in the background
# curl http://backend:9100/metrics for metrics

EXPOSE 8080

ENTRYPOINT [ "sh", "../config/autoLaunch.sh" ]
# CMD ["daphne", "-p", "8080", "source.asgi:application"]
CMD [ "tail", "-f", "/dev/null"]
