FROM python:alpine

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# RUN pip install --upgrade pip

WORKDIR /app/source

COPY ./config /app/config


# RUN mkdir -p /app/staticfiles/
# RUN apt update && apt install wget -y
# RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.1.1/node_exporter-1.1.1.linux-amd64.tar.gz

# RUN tar xvfz node_exporter-*.*-amd64.tar.gz
# RUN ./node_exporter & in the background
RUN chmod -R +x /app/config

EXPOSE 8080

# ENTRYPOINT [ "sh", "/app/config/autoLaunch.sh" ]
# CMD [ "python", "manage.py", "runsever", "0.0.0.0:8080"]
CMD [ "tail", "-f", "/dev/null"]

# curl http://backend:9100/metrics for metrics
