# Generated by Django 5.1.2 on 2024-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='users',
            new_name='senders',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='password',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
