# Generated by Django 5.0.9 on 2024-11-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemove',
            name='y_position',
        ),
    ]
