/* eslint-disable @next/next/no-img-element */
import type { Metadata } from 'next';
import { Inter, Coustard } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  // variable: '--font-Inter',
  weight: ['400', '700'],
});

const coustard = Coustard({
  subsets: ['latin'],
  weight: ['400', '900'],
  // variable: '--font-coustard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen w-full items-end justify-center overflow-auto bg-[#13191D] md:items-center">
          <div className="h-[90%] w-full">
            <div className="mb-[-75px] flex h-[150px] w-full items-center justify-center md:mb-[-80px] lg:hidden">
              <img
                src="/landing-page-logo.svg"
                alt="logo"
                className="size-[150px] md:size-[200px]"
              />
            </div>
            <div className="flex size-full items-start justify-center lg:items-center">
              {/* the max/min with/height of the div under must be defined in the input and text bars of the form so this dive resizes itself based on the children  */}
              <div className="flex size-full md:size-[85%] md:max-h-[850px] md:min-h-[500px] md:max-w-[1517px]">
                {children}
                <div className="z-[1] order-2 hidden h-full w-[500px] items-center lg:flex">
                  <img src="/logo.svg" alt="logo" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
