# frontend/Dockerfile
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Install dependencies
# COPY package.json yarn.lock ./
# RUN yarn install

# Copy the project files
COPY . .

# Build the application
# RUN yarn build

EXPOSE 3000

# ENTRYPOINT [ "sh", "../config/autoDeploy.sh" ]
# CMD ["npm", "next", "dev", "-H", "0.0.0.0", "-p", "3000"]
CMD ["tail", "-f", "/dev/null"]
