
###############
GET http://localhost:8080/chat/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MTUyMzQ2LCJpYXQiOjE3MzUxNDk5NDYsImp0aSI6IjhlMTdiYjU3MWVlNDQxMjI4Yjg4YTk0ZGIzZTIyNjYyIiwidXNlcl9pZCI6Mn0.f2Dd1ITysF3snEHT5AghjvFp-9oJ2ntEXj3aGH3XxGA


#########
GET http://localhost:8080/chat/1/messages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MTUyMzQ2LCJpYXQiOjE3MzUxNDk5NDYsImp0aSI6IjhlMTdiYjU3MWVlNDQxMjI4Yjg4YTk0ZGIzZTIyNjYyIiwidXNlcl9pZCI6Mn0.f2Dd1ITysF3snEHT5AghjvFp-9oJ2ntEXj3aGH3XxGA

#########