
POST http://localhost:8080/auth/signup/
Content-Type: application/json

{
    "username": "ola",
    "email": "ola@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}

########

GET http://localhost:8080/oauth/login/42

########

GET http://localhost:8080/auth/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxOTQxNzY3LCJpYXQiOjE3MzE5Mzk5NjcsImp0aSI6IjQxYTllODlkYjFkYzRiMDU4OTBjMTNiZWI4N2Q0MWY3IiwidXNlcl9pZCI6MX0.drTL3NdyZ2G40xZl3J3NRCYQ3Mj5q5Z045K0gOtR5tU
########
########

POST http://localhost:8080/chat/ch/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxOTQxNzY3LCJpYXQiOjE3MzE5Mzk5NjcsImp0aSI6IjQxYTllODlkYjFkYzRiMDU4OTBjMTNiZWI4N2Q0MWY3IiwidXNlcl9pZCI6MX0.drTL3NdyZ2G40xZl3J3NRCYQ3Mj5q5Z045K0gOtR5tU
Content-Type: application/json

{
    "senders": "ola"
}
########

GET http://localhost:8080/chat/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxOTQxNzY3LCJpYXQiOjE3MzE5Mzk5NjcsImp0aSI6IjQxYTllODlkYjFkYzRiMDU4OTBjMTNiZWI4N2Q0MWY3IiwidXNlcl9pZCI6MX0.drTL3NdyZ2G40xZl3J3NRCYQ3Mj5q5Z045K0gOtR5tU

########

POST  http://localhost:8080/chat/1/messages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxOTQxNzY3LCJpYXQiOjE3MzE5Mzk5NjcsImp0aSI6IjQxYTllODlkYjFkYzRiMDU4OTBjMTNiZWI4N2Q0MWY3IiwidXNlcl9pZCI6MX0.drTL3NdyZ2G40xZl3J3NRCYQ3Mj5q5Z045K0gOtR5tU
Content-Type: application/json

{
    "receiver":"ola",
    "content":"hey body"
}

########

### WebSocket Connection Test
WEBSOCKET ws://127.0.0.1:8080/ws/chat/1/

# # Send a message
# > websocket-send
# {
#     "type": "websocket.send",
#     "message": "Hello, WebSocket!"
# }


# /
# # Optional: multiple sends
# > websocket-send
# {
#     "type": "websocket.send",
#     "message": "Another test message"
# }