
POST http://localhost:8080/auth/signup/
Content-Type: application/json

{
    "username": "dasdasdas",
    "email": "dsadasdasd@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}

########

POST http://localhost:8080/auth/l/
Content-Type: application/json

{
    "username": "xasdasdvs",
    "email": "vscodevscode@gmail.com",
    "password": "dasdasdsadasddasdasdad",
    "password2": "dasdasdsadasddasdasdad"
}

########

GET http://localhost:8080/auth/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNTQ2NjQ0LCJpYXQiOjE3MzE1NDQ4NDQsImp0aSI6ImQxODc1MGYwNWIyMTQ0MDViNGVmMzVhOGRmYjYzMjM2IiwidXNlcl9pZCI6M30.4bOJNppxJJnoe1ck_E6X2jLRH0jcy9UQIV_TiK5370g


########
########

GET http://localhost:8080/chatoom/lobby
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNTQ2NjQ0LCJpYXQiOjE3MzE1NDQ4NDQsImp0aSI6ImQxODc1MGYwNWIyMTQ0MDViNGVmMzVhOGRmYjYzMjM2IiwidXNlcl9pZCI6M30.4bOJNppxJJnoe1ck_E6X2jLRH0jcy9UQIV_TiK5370g


########
// access
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNTQ0NjUxLCJpYXQiOjE3MzE1NDI4NTEsImp0aSI6IjM4ZGI1MjllNDExMjQ3MGJiZThmZDAzZmZkMTc1MWU1IiwidXNlcl9pZCI6MX0.P1JiLlPUq7JS5zDcBrKRDv7lZmNWVlHJsp75lCvFz_c
// refrech
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTgwMjA1MSwiaWF0IjoxNzMxNTQyODUxLCJqdGkiOiI0YWNhYTEwN2NlNzc0OGE2ODM0Y2M0ZmFkNDhkYWI2ZCIsInVzZXJfaWQiOjF9.lb1p4NlYcS6HgeUGOJJegsegfxd3MKRnBtAqk0oYAZQ
# GET http://localhost:8080/auth/generate-uri/

# ############
# #
# GET http://localhost:8080/auth/generate-uri/



# GET http://localhost:8080/auth/generate-uri/



# GET http://localhost:8080/auth/generate-uri/
