############--------_JTW_--------------############


POST http://localhost:8080/api/JWT/token/
Content-Type: application/json

{
    "username": "xxx",
    "password": "csfdsgopxabcvbdfgdfg"
}

########---------signup------_#########

POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "kadigh",
    "email": "kadigh@gmail.com",
    "password": "csfdsgopxabcvbdfgdfg",
    "password2": "csfdsgopxabcvbdfgdfg"
}

###   ###   ##  ## ###  ##  ## ### ##
POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "mehdi",
    "email": "mehdi@gmail.com",
    "password": "csfdsgopxabcvbdfgdfg",
    "password2": "csfdsgopxabcvbdfgdfg"
}

### ### ####  ### ###  #####----  ----

POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "hind",
    "email": "hindo@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}
###  ####   ###  ### ## ####  ###

POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "SadUser",
    "email": "SadUser@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}
##########-----LIST----############ 

GET http://localhost:8080/relations/notifications/
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNjg1MDI0LCJpYXQiOjE3MzM1OTg2MjQsImp0aSI6IjczMDQwYWE2ZTU2MTQ4YTJhMGY5M2Q1YjQ2OTk3NjFiIiwidXNlcl9pZCI6NH0.PzR58hnXJmIFW0vNFqFW9TJXGapkZLdR8Ffla0WIVsQ

########

GET http://localhost:8080/api/users/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMDcyOTA0LCJpYXQiOjE3MzMwNzExMDQsImp0aSI6IjAxNjE3MmUyZjdjNTRmMTQ4ZjdmMzBmMWY4Y2U4YzcxIiwidXNlcl9pZCI6NX0.F6CCQG6ruEwRAgVzrMlMzin0Krc00aPbe0BS5As-3dA



# #########-----me---- ####
# backend   | Not Found: /api/users/me/
# backend   | HTTP GET /api/users/me/ 404 [0.03, 172.18.0.1:64634]
#######


GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMDcwNDg1LCJpYXQiOjE3MzMwNjg2ODUsImp0aSI6IjY1YzYxOGUzYTEyNDRjYzU4NGFlNTBmOWEzMDk5YjkxIiwidXNlcl9pZCI6NX0.njthXe5ZdAMp9_W1WgIfnbwWZj1tI04O9hq3uJ1Jai4





###-----------FRIENDS------##############
GET http://localhost:8080/relations/players/
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNzcxODQxLCJpYXQiOjE3MzM2ODU0NDEsImp0aSI6IjJkY2ExYzFhNWM0NzQwODE4MWM4Yzk4MDRiMGUyNjMxIiwidXNlcl9pZCI6MTF9.BmkYIbkXwWlvNQ5K7p7juHl4Ke0Nj0r3NyjvFGOqNzs

## ### ## ### # ##### #####



#
###

OPTIONS http://localhost:8080/relations/notifications/
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNzcxODQxLCJpYXQiOjE3MzM2ODU0NDEsImp0aSI6IjJkY2ExYzFhNWM0NzQwODE4MWM4Yzk4MDRiMGUyNjMxIiwidXNlcl9pZCI6MTF9.BmkYIbkXwWlvNQ5K7p7juHl4Ke0Nj0r3NyjvFGOqNzs



## ### ## ### # ##### #####

#########

POST http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMjc2NTg3LCJpYXQiOjE3MzMyNzQ3ODcsImp0aSI6IjRiYTI0MjNhMGRkZTQyNzFhYzM5NDdlNjY4ZmFlYTg0IiwidXNlcl9pZCI6NX0.FDpLjR5KCKuX5dDfZalN8b8dvIzUpsN0sf34DLzw9j4
Content-Type: application/json

{
    "receiver":"pipo"
}
### #  ## ##

POST http://localhost:8080/relations/friends/accept/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMjc1ODg3LCJpYXQiOjE3MzMyNzQwODcsImp0aSI6ImI3ZDc1MzY3NzVkODQwZWE5MjcwYjc2YWI0MzNmNGM1IiwidXNlcl9pZCI6NX0.2z1oWMw5jDMjDTNaIfXx8ymBUkjEXWUlizdfjWQc3Mc
Content-Type: application/json

{
    "sender":"ali"
}
### ## # 














###

POST http://localhost:8080/api/JWT/token/refresh
# 

############--------------CHAT-------###############

GET http://localhost:8080/chat/list/
Cookie eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTczMjI0LCJpYXQiOjE3MzMxNzE0MjQsImp0aSI6ImJkYjY0MGRiMGM1YzRlMDU5MTE5Nzg3MWE2YWViMjQ0IiwidXNlcl9pZCI6Mn0.bcBgqzclgoWTEt3zOyu5iD8uujmdbgM1cv3P4YVQSZE

####
POST http://localhost:8080/chat/ch/
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNjk0NjU0LCJpYXQiOjE3MzM2MDgyNTQsImp0aSI6IjkzMWNiZGJhMjJiOTQ2NDdiNjllOGRiMmY5YzQ5OWVhIiwidXNlcl9pZCI6NH0.T03-M8aSTl5RAyPrC5qYnzsnQilodV-Ytx7CE5H3Tks
Content-Type: application/json

{
    "senders":"mery"
}

######

GET  http://localhost:8080/chat/1/messages/
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODIzOTkyLCJpYXQiOjE3MzQ3Mzc1OTIsImp0aSI6IjEzMTg5MjRjMGI5NzRjMGJhNDU4Y2MxMWRkMmYwN2NlIiwidXNlcl9pZCI6MX0.8LWX5LDSOwLYtlFp-GeEiPVJO4y0MNILrKw_7MUUChk


########
