


POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "ali",
    "email": "ali@gmail.com",
    "password": "csfdsgopxabcvbdfgdfg",
    "password2": "csfdsgopxabcvbdfgdfg"
}

######################

GET http://localhost:8080/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMDAzMzU1LCJpYXQiOjE3MzMwMDE1NTUsImp0aSI6IjZiOTYwZWU0ZjU3MjQwODA4Yjc1MWRkZGU2Njk0MWI1IiwidXNlcl9pZCI6MX0.emVOBBsPqqjSBSY-UvFg4CP5mH2DhHf5DxCBrrHca-4


###
POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "hiya",
    "email": "hiya@gmail.com",
    "password": "csfdsgopxabcvbdfgdfg",
    "password2": "csfdsgopxabcvbdfgdfg"
}

###################### 

GET http://localhost:8080/relations/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzU2MTkxLCJpYXQiOjE3MzI3NTQzOTEsImp0aSI6ImE1MWE3ZGU2YjdlMjQ4MzQ4MjE3MWZhMjgwNTgxZWMwIiwidXNlcl9pZCI6M30.lomaKh-0_TUc1jUXnnvp2DP3_e_05U29rSAjw41Q-qs

######################

POST http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzU0NzIzLCJpYXQiOjE3MzI3NTI5MjMsImp0aSI6ImMxMzFhY2QyMWQ2YzQyODNhMjdmYjAzNDNiZGM0MTg3IiwidXNlcl9pZCI6M30.uWwWu_BAwRD1wY65qvpD5WPb3-r9bk3C10j3G64yA0Y
Content-Type: application/json

{
    "receiver":"meryem"
}
########

POST http://localhost:8080/relations/friends/accept/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzU2MTI5LCJpYXQiOjE3MzI3NTQzMjksImp0aSI6IjJjZDJiOTRiZTAxZTQwODA4ZjZjM2M3Y2I3ZWU4ODY1IiwidXNlcl9pZCI6M30.0-rPtXlFgXnQRCzyE4MFtdOKRiIFy2f--cMt4cvchvc
Content-Type: application/json

{
    "sender":"meryem"
}
######



POST http://localhost:8080/api/JWT/token/
Content-Type: application/json

{
    "username": "ali",
    "password": "csfdsgopxabcvbdfgdfg"
}
######################

POST http://localhost:8080/api/signup/
Content-Type: application/json

{
    "username": "opa123",
    "email": "opa123@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}
######################

POST http://localhost:8080/api/signup/
Content-Type: application/json

{
    "username": "opa12345",
    "email": "opa12345@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}

########

GET http://localhost:8080/api/oauth/login/42

    # "email": "tokenjdid@gmail.com",
    # "password2": "csfdsgbcvbdfgdfg",
########



# POST http://localhost:8080/api/JWT/token/refresh

GET http://localhost:8080/api/ /all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMDAzMzU1LCJpYXQiOjE3MzMwMDE1NTUsImp0aSI6IjZiOTYwZWU0ZjU3MjQwODA4Yjc1MWRkZGU2Njk0MWI1IiwidXNlcl9pZCI6MX0.emVOBBsPqqjSBSY-UvFg4CP5mH2DhHf5DxCBrrHca-4

########

POST http://localhost:8080/chat/ch/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U
Content-Type: application/json

{
    
}


########
POST http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U
Content-Type: application/json

{
    "receiver": "ola"
}
########

GET http://localhost:8080/chat/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMDEwODI4LCJpYXQiOjE3MzMwMDkwMjgsImp0aSI6IjJjNzRiYWU3NDA3MzRiOGRhY2RmNzc3OGRmODVlYWNlIiwidXNlcl9pZCI6MX0.koY_CfsHVsZoQzTg4poKiBs8uDN8CfdCmUSgO-z2bmo
########
GET http://localhost:8080/relations/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U

########


POST  http://localhost:8080/chat/1/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U
Content-Type: application/json

{
    "receiver":"zb",
    "content":"hey body"
}

########

### WebSocket Connection Test
WEBSOCKET ws://127.0.0.1:8080/ws/chat/1/

# # Send a message
# > websocket-send
# {
#     "type": "websocket.send",
#     "message": "Hello, WebSocket!"
# }


# /
# # Optional: multiple sends
# > websocket-send
# {
#     "type": "websocket.send",
#     "message": "Another test message"
# }
