
POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "ali",
    "email": "ali@gmail.com",
    "password": "csfdsgopxabcvbdfgdfg",
    "password2": "csfdsgopxabcvbdfgdfg"
}

######################
POST http://localhost:8080/api/auth/signup/
Content-Type: application/json

{
    "username": "youssra",
    "email": "youssra@gmail.com",
    "password": "csfdsgopxabcvbdfgdfg",
    "password2": "csfdsgopxabcvbdfgdfg"
}



#######
GET http://localhost:8080/relations/players/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTAwODY2LCJpYXQiOjE3MzMwOTkwNjYsImp0aSI6ImQ3ZjAyMmU0MjUyMDQwOTRiNzg5YjcyYTg1NzJlMWZkIiwidXNlcl9pZCI6M30.5ViJ8wJKodi1GhAiLaglRl34-QEtPJqxPRJPtB-I1sU
###################### 

GET http://localhost:8080/relations/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTAzNzcwLCJpYXQiOjE3MzMxMDE5NzAsImp0aSI6ImQ2ODk1YTdkOWRlNDRmYWM5ZmJkODhkY2YzMWMxYjQwIiwidXNlcl9pZCI6NH0.aTmTarmfm0omUpBSBtyDYd92s6GZBeGw1PqUXmuWyUQ

# ####

######################

###################### 
POST http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTAyOTIwLCJpYXQiOjE3MzMxMDExMjAsImp0aSI6Ijc2YWM3ODExMWQwNDQ5ZDhiMzRmYTlhMzJiZGU0MzJjIiwidXNlcl9pZCI6Nn0.9KS_nyX8MWL6uRYdqZzHWvJtIYXWVDpDXJcmtlrWR3g
Content-Type: application/json

{
    "receiver":"mery"
}
########

POST http://localhost:8080/relations/friends/accept/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTAyOTIwLCJpYXQiOjE3MzMxMDExMjAsImp0aSI6Ijc2YWM3ODExMWQwNDQ5ZDhiMzRmYTlhMzJiZGU0MzJjIiwidXNlcl9pZCI6Nn0.9KS_nyX8MWL6uRYdqZzHWvJtIYXWVDpDXJcmtlrWR3g
Content-Type: application/json

{
    "sender":"test"
}
######



POST http://localhost:8080/api/JWT/token/
Content-Type: application/json

{
    "username": "ali",
    "password": "csfdsgopxabcvbdfgdfg"
}
######################

POST http://localhost:8080/api/signup/
Content-Type: application/json

{
    "username": "opa123",
    "email": "opa123@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}
######################

POST http://localhost:8080/api/signup/
Content-Type: application/json

{
    "username": "opa12345",
    "email": "opa12345@gmail.com",
    "password": "csfdsgbcvbdfgdfg",
    "password2": "csfdsgbcvbdfgdfg"
}

########

GET http://localhost:8080/api/oauth/login/42

    # "email": "tokenjdid@gmail.com",
    # "password2": "csfdsgbcvbdfgdfg",
########



# POST http://localhost:8080/api/JWT/token/refresh

GET http://localhost:8080/api/list/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODI2OTY1LCJpYXQiOjE3MzI4MjUxNjUsImp0aSI6IjYzNjU1YzM5NDNjMjQ0MjBiNjIwOWU0MWE1OTQ0ODE1IiwidXNlcl9pZCI6MX0.21KdLFv3fuuw4dl4vMCOgmRIZQTo2--gq-IMmOfdtfM
########

POST http://localhost:8080/chat/ch/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U
########
POST http://localhost:8080/relations/friends/invite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U
Content-Type: application/json

{
    "receiver": "ola"
}
########

GET http://localhost:8080/chat/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U

########
GET http://localhost:8080/relations/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U

########


POST  http://localhost:8080/chat/1/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTU0MTM3LCJpYXQiOjE3MzI1NTIzMzcsImp0aSI6IjY2NzQ3MjliNGE4YTQ0NTc4MWExODVhODBmYTUyM2NjIiwidXNlcl9pZCI6M30.oyDOk7ZR_PmUqUughPjLsHdsOKJ_n1Af-pyM6Us4G3U
Content-Type: application/json

{
    "receiver":"zb",
    "content":"hey body"
}

########

### WebSocket Connection Test
WEBSOCKET ws://127.0.0.1:8080/ws/chat/1/

# # Send a message
# > websocket-send
# {
#     "type": "websocket.send",
#     "message": "Hello, WebSocket!"
# }


# /
# # Optional: multiple sends
# > websocket-send
# {
#     "type": "websocket.send",
#     "message": "Another test message"
# }
