# Generated by Django 4.2.15 on 2024-10-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='otp_secret_key',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
